### ISSUE TITLE
Assign harvested datasets to topics depending on the source configuration

### ISSUE THREAD

**Issue by amercader** [okfn/ckanext-lacounts#37]
# Overview

Harvested datasets from a particular source should be automatically added to a particular topic, defined as a configuration option in the harvest source. The [CKAN harvester](https://github.com/ckan/ckanext-harvest#the-ckan-harvester) supports this option (`default_groups`).

# Tasks
- @roll
  - [x] Add a UI to set this config option in the harvest source form ([example](https://github.com/GSA/ckanext-geodatagov/blob/master/ckanext/geodatagov/plugins.py#L145))
- TBD
  - [ ] Implement logic similar to `default_groups` in the rest of harvesters (ideally in the common place, see #38)

**Comment by roll** [comment]
@brew 
@amercader 
I think we definitely need to have the form field for `topics` instead of json `config`. It means we need to extend `ckanext-harvest` at `ckanext-lacounts` level and e.g. save `topics` as `source.config.default_topics`.

Another question is on which level we should apply these topics. It's already implemented for `CKANHarvester` and probably it makes sense just port this code to Socrate/ESRI. I think it will be more consistent across harvesters, provide better new plugins and cost only copy-pasting from the ckan harvester.

For a reference here is the code for the ckan harvester - https://github.com/ckan/ckanext-harvest/blob/master/ckanext/harvest/harvesters/ckanharvester.py#L124-L146

**Comment by roll** [comment]
@brew 
@amercader 
I've done the first chunk of work here:
- https://github.com/okfn/ckanext-lacounts/pull/59
- https://github.com/okfn/docker-ckan-lacounts/pull/5

What we have at the moment:
- we can set topics via UI forms
- topics are stored as `config.default_groups`

It's fully functional for ckan harvester.

![ckan](https://user-images.githubusercontent.com/557395/45092385-db869b80-b11d-11e8-8b86-11c5eff4c463.png)

What's left:
- fix the way we hook `default_groups` into `condig` here - https://github.com/okfn/ckanext-lacounts/pull/59
- add `default_groups` logic to `SocrataHarvester` as it is for `CKANHarvester` - https://github.com/ckan/ckanext-harvest/blob/master/ckanext/harvest/harvesters/ckanharvester.py#L124-L146 (if we all think that's the way to go)

**Comment by roll** [comment]
Implemented a better version here - https://github.com/okfn/ckanext-lacounts/issues/76
