### ISSUE TITLE
Some uploaded images are destroyed on every staging deployment

### ISSUE THREAD

**Issue by roll** [okfn/ckanext-lacounts#96]
# Overview

It happens for:
- featured visualisation image (via admin)
- featured stories image (via edit story)

**Comment by amercader** [comment]
I made a redeploy and the images were there. Let's keep an eye on it but maybe it was just a glitch

**Comment by amercader** [comment]
The S3 backend was not enabled so images where uploaded to the container and so destroyed on each deploy.

After enabling the backend most of the uploads work, but not the one for the featured image, because that particular request is served by Flask (https://github.com/okfn/ckanext-s3filestore/issues/23)

**Comment by amercader** [comment]
Fixed in okfn/ckanext-s3filestore and deployed
